@startuml
title VideoMonitoringService Component Diagram

top to bottom direction

!include ..\templates\C4_Component.puml

Container_Boundary(SmartHomeSystem, "SmartHome System") {
  Container(VideoMonitoringService, "VideoMonitoringService", "Python, Flask")
  Container(Database1, "Database", "PostgreSQL", "Stores sensors state")
  Container(Database2, "Database", "PostgreSQL", "Stores video monitoring data")
}

Container(VideoMonitoringService, "VideoMonitoringService", "Python, Flask") {
  Component(VideoMonitoringQueriesAPI, "VideoMonitoringQueriesAPI", "Handles queries")
  Component(VideoMonitoringCommandsAPI, "VideoMonitoringCommandsAPI", "Handles commands")
  Component(StateManager, "StateManager")
  Component(CommandProcessor, "CommandProcessor")
}

Rel(VideoMonitoringQueriesAPI,StateManager,"Queries")
Rel(VideoMonitoringCommandsAPI,CommandProcessor,"Commands")
Rel(StateManager,Database1,"Reads data")
Rel(CommandProcessor,Database2,"Writes data")
@enduml